
export const STYLE_CONSTANTS = {
  margin: {
    NO_HEADER_MAIN_MARGIN_TOP: 50,
    NO_HEADeR_MAIN_MARGIN_TOP_S: 50,
    NO_HEADER_LOGO_MARGIN_BOTTOM: 100,
    NO_HEADER_LOGO_MARGIN_BOTTOM_S: 50
  }
};
